### ISSUE TITLE
Method cache is invalid when partial class reload

### ISSUE THREAD

**Issue by jwistrom** [briandilley/jsonrpc4j#210]
Hi
I use Spring boot and the live reload feature. This entails that the project classes are loaded by a separate classloader than the classes of any dependency (including jsonrpc4j in my case). This means that the method cache in the class `ReflectionUtil` becomes invalid and in turn renders a "IllegalArgumentException: object is not an instance of declaring class" when trying to invoke a method that is not present on the target. Is there a possibility to include some way to get around that cache (ignore or invalidate the cache)?

**Comment by mslipper** [comment]
I can take a look this weekend.

**Comment by jwistrom** [comment]
Any news on this?

**Comment by mslipper** [comment]
Apologies - some things came up. I'll take a look within the next 24 hours.

**Comment by mslipper** [comment]
I'll add a method that clears the cache. PR inbounard, can you take a look @jwistrom ?

**Comment by mslipper** [comment]
Looks like there already is a method - `clearCache`. It's public, so you should be able to hook it into `RestartListener`. See https://github.com/spring-projects/spring-boot/blob/v1.5.9.RELEASE/spring-boot-devtools/src/main/java/org/springframework/boot/devtools/restart/RestartListener.java.

**Comment by mslipper** [comment]
Released in 1.5.3.

**Comment by jwistrom** [comment]
Great, thanks. Any estimate on deployment to maven central?

**Comment by mslipper** [comment]
It should be deployed already. I pushed it as part of the release.

**Comment by jwistrom** [comment]
Still nothing on maven central...weird

**Comment by mslipper** [comment]
I'll debug today. Sorry for the wait here.

**Comment by jwistrom** [comment]
no worries. thanks!

**Comment by jwistrom** [comment]
Hi. Have you found any reason why v. 1.5.3 was not pushed to maven central? I still can't find it there

**Comment by mslipper** [comment]
I'll redeploy it. Should have an answer within 24 hours.

**Comment by mslipper** [comment]
Try it now - should be up:

![screen shot 2018-01-31 at 3 36 29 pm](https://user-images.githubusercontent.com/67953/35653324-89bbb49c-069c-11e8-9c66-ca5c2836c4e1.png)
